title: Installing recommended software
hero_image: images/banner.png
description: how to install recommended software
version: 4
listed: false
copyedit: false
last_tested: "2018-06-14"
steps:
  - title: Installing recommended software
